### PR TITLE
Added TransferApi class and getTransfers() method. 

### PR DESCRIPTION
**Pull request by edmundpf**
Gets deposits and withdrawals of a profile_id or all profiles. All tests passing. Added under src/transfer according to README.md contribution guide.

### CODE REVIEW

**Comment by bennyn** [comment]
Hi @edmundpf, I very much welcome your contribution! Can you please submit your PR without changes to the `version` field in `package.json` and without updates in the `docs` directory? Those changes will be done automatically when I run the `release` script.

**Comment by edmundpf** [comment]
> Hi @edmundpf, I very much welcome your contribution! Can you please submit your PR without changes to the `version` field in `package.json` and without updates in the `docs` directory? Those changes will be done automatically when I run the `release` script.

Sure thing!

**Comment by edmundpf** [comment]
@bennyn pushed a new commit with only the new TransferAPI changes

**Comment by bennyn** [comment]
**Great.** I am merging this and afterwards I will streamline all paginated requests and push a new version of "coinbase-pro-node". 🙂

**Comment by bennyn** [comment]
@edmundpf your changes went live with [coinbase-pro-node v2.6.0](https://www.npmjs.com/package/coinbase-pro-node/v/2.6.0). 👍

**Comment by edmundpf** [comment]
> @edmundpf your changes went live with [coinbase-pro-node v2.6.0](https://www.npmjs.com/package/coinbase-pro-node/v/2.6.0). 👍

@bennyn awesome! thank you sir

**Pull request merged**
