### PR TITLE
Pagination Implementation

### PR DESCRIPTION
**Pull request by aliasbody**
This is a basic pagination implementation, I'll be more than glad to implement the full pagination just wanted to better discuss code design to be sure that this follows the idea that @bennyn had.

The actual implementation implies a big change in the way the callback results are handled since it will devide them in two sections:
- **data** : Returns the actual data (unmodified)
- **pagination** : Returns 3 settings `limit`, `after` and `before`

Everything remains the same naming as in the officiel API doc https://docs.pro.coinbase.com/#pagination

### CODE REVIEW

**Comment by bennyn** [comment]
Hi @aliasbody, I really appreciate your contribution. Pull requests like this show me that it is really worth publishing open source code!

I am okay with adding a `pagination` parameter to all endpoints which return arrays. But it should be an optional parameter and when passing it the limit should be required.

May I ask why you return `RESTData` and not just the `response.data` directly? I would like to avoid changing the response type as it will be a breaking change to the API of this library.

**Comment by aliasbody** [comment]
Hi @bennyn, thank you :)

I can implement this quickly, I'll try to do this until the end of the day and send new commits.

As for the RESTData being returned, I don't really like the approach because we loose the type casting and thus the autocomplete on some IDE's like PHPStorm (which I'm using). But we need the before and after values (which is an int) that is used for pagination. In order to avoid this and simply return the response.data I could do one of two things:
- Encapsulate the response from the original method in order to let the code as it is an only add pagination when needed (I need to see more in details how your code was written in order to respect the structure)
- Not using pagination at all and simply handle pagination on the Library itself by sending the full result. This is clearly not the best approach.

I'll see if I can think of anything better.

**Comment by aliasbody** [comment]
Just a quick update. I don't think it's possible to do this without changing either the output (because it returns an array of objects and we need to introduce a new pagination object), or by using a callback instead of a promise (since it allows multiple values).

The best way to change this (without much change) is by using a `destructing array or object,` but it would break current code anyway since without it on the `then` function it would just return the object as it is (the `RESTData`).

What do you propose to do here?

**Comment by bennyn** [comment]
Can you give me an example payload when using pagination and when not using pagination? I want to see the difference in the response payload.

**Comment by aliasbody** [comment]
@bennyn Here is an example of a payload with pagination:
```javascript
{
  "result": [
    {
      "id": "100",
      "created_at": "2014-11-07T08:19:27.028459Z",
      "amount": "0.001",
      "balance": "239.669",
      "type": "fee",
      "details": {
        "order_id": "d50ec984-77a8-460a-b958-66f114b0de9b",
        "trade_id": "74",
        "product_id": "BTC-USD"
      }
    }
  ],
  "pagination": {
    "limit": 100,
    "before": 278300,
    "after": 280000
  }
}
```

A non paginated payload would looke exactly as it is:
```javascript
[
  {
    "id": "100",
    "created_at": "2014-11-07T08:19:27.028459Z",
    "amount": "0.001",
    "balance": "239.669",
    "type": "fee",
    "details": {
      "order_id": "d50ec984-77a8-460a-b958-66f114b0de9b",
      "trade_id": "74",
      "product_id": "BTC-USD"
    }
  }
]
```

Of course this is not optimal and I agree with you. The most important information that needs to be passed is the `after` and `before` value (those are sent back in the header for every paginated request) and thus they need to have a way to be read. If we were using a callback this wouldn't be a question because we would simply add a return param (`pagination`) that would not have any impact on actual code and for future usages would provide a way to simply read the pagination value and send it to have the next page of information. But a promise doesn't allow to do that, a destructing would just make it a breaking change.

**Comment by bennyn** [comment]
Thanks for providing those samples. If I am not mistaken you want to return the response headers `CB-BEFORE` and `CB-AFTER` to make requests for pages after the initial request? Are these headers already available when not passing `before` and `after` query params?

**Comment by aliasbody** [comment]
@bennyn Yes it's already part of any paginated request even when no before/after param is passed.

**Comment by bennyn** [comment]
Ok! Then we are getting there. I just made a quick test:

```
const accounts = await client.rest.account.listAccounts();
const accountId = accounts[0].id;
const accountHistory = await client.rest.account.getAccountHistory(accountId);
```

```ts
async getAccountHistory(accountId: string): Promise<AccountHistory[]> {
  const resource = `${AccountAPI.URL.ACCOUNTS}/${accountId}/ledger`;
  const response = await this.apiClient.get<AccountHistory[]>(resource);
  console.log('after', response.headers['cb-after']);
  console.log('before', response.headers['cb-before']);
  return response.data;
}
```

For me the "after" and "before" values have been `undefined`. I guess it's because I don't have any recent activity.

I am okay with changing the method's signature to:

```typescript
getAccountHistory(accountId: string, pagination: Pagination): Promise<{data: AccountHistory[], pagination: {after?: string, before?: string}}>
```

Let's not add the limit to the pagination of the response because it's not a response coming from Coinbase Pro. We should also avoid the `RESTData` for now because we can express this type as shown above and omit the `data: any;`.

For the `Pagination` type of the request I am suggesting to make the `limit` mandatory:

```ts
export interface Pagination {
  before?: string;
  after?: string;
  limit: number;
}
```

Does this make sense?

**Comment by aliasbody** [comment]
@bennyn Perfect for me, but we have to keep in mind that this will be a breaking change (even if only for the paginated requests). I'll make the changes and make a new push.

**Comment by aliasbody** [comment]
@bennyn That should do it. Let me know what you think.

**Comment by bennyn** [comment]
Looks nice and clean. I like it! 👌 

Can you add (and export) a constant for the `MAXIMUM_PAGINATION_LIMIT` which is `100`? After that I will merge your PR.

**Comment by aliasbody** [comment]
@bennyn Just had it removed on my last commit, here it is again.

**Comment by bennyn** [comment]
Thank you for this great contribution! Because it's a breaking API change I published it with a major version bump. Your PR starts the beginning of coinbase-pro-node v2. 🍾

**Comment by aliasbody** [comment]
@bennyn Thank you for keeping this library updated :) Also if there is anything else I can help, please let me know.

**Comment by bennyn** [comment]
Hey @aliasbody, today I implemented [request signing](https://github.com/bennyn/coinbase-pro-node/pull/142/files) for WebSocket subscriptions. If you like, you can help me implementing the last missing endpoints. I made a list of every endpoint which is missing: https://github.com/bennyn/coinbase-pro-node/issues/17

**Pull request merged**
